### ISSUE TITLE
StreamStickers is not a lurker bot

### ISSUE THREAD

**Issue by EthanBlaisAlarms** [arrowgent/Twitchtv-Bots-List#13]
StreamStickers is on the list of lurker bots, however it is a good bot used by https://www.streamstickers.com/

**Comment by arrowgent** [comment]
hmmm, not a lurker bot.  this seems reasonable
my list is fairly automated, if a user visits 150+ channels in 24 hours it gets added to the list
ive added it to my "goodbots" so that it will not automatically get added again
thank you

https://github.com/arrowgent/Twitchtv-Bots-List/commit/265755510f82281ed639e73a33a00d8d770806f8
