### ISSUE TITLE
"NightmareJoker2" is NOT A BOT

### ISSUE THREAD

**Issue by dori4n** [arrowgent/Twitchtv-Bots-List#32]
See #24 

Removed on November 16th 2023 with https://github.com/arrowgent/Twitchtv-Bots-List/commit/83a0ed9a2cf540edceaf7102aed18f33d443b8b8, but readded two weeks later with https://github.com/arrowgent/Twitchtv-Bots-List/commit/ee84bb9a6b5726d67a2871d2b39f5d520b6158cf

😔

**Comment by arrowgent** [comment]
surely using a bot to watch hundreds of channels is not an acceptable use if they are not invited to do so.

if i invited your bot to come stay in my chat then 2000 other people do the same, that is an example of a goodbot because they respect that i instructed them to do that.
if nobody asked them to go do that, and they use the bot/irc api to join chats without asking and then staying there indefinitely: that is not ok.

especially if said bot has no interface, doesnt report what it does, and most likely infact doesnt do anything (~useful)

as stated before: a regular human user will not exceed being in 100-150 different chats in a 24 hour period.  there is no way a reasonable person of intelligence is going to simultaneously be in those chats at the same time.
20-40 chats? yes that is a reasonable thing for a 24 hour time frame for a real human being using the twitch interface to interact with the video stream and or chat.


on second thought.  i will not remove nightmarejoker2 again.  2 weeks later was enough time for them to stop lurking if it was reported once.

with recent twitch backend improvements they have removed most bots ability to lurk unless they are official bots.  thus removing the need for this list and hunting down lurker bots

that is all.
